In [33]:
import torch as th
import torch

In [ ]:
# Scalar tensor
t_scalar = th.tensor(5)



torch.Tensor

In [7]:
# 1 D tensor

t_1D = th.tensor([1,2,3,4])

t_1D.shape

torch.Size([4])

In [16]:
# 2 D tensor

t_2D = th.tensor([[1, 2, 3, 4],
                  [1, 2, 3, 4],
                  [1, 2, 3, 4],
                 ])

t_2D.shape

torch.Size([3, 4])

In [14]:
# 3 D tensor

t_3D = th.tensor([
                 [[1, 2, 3, 4], [1, 2, 3, 4]],
                 [[1, 2, 3, 4], [1, 2, 3, 4]],
                 [[1, 2, 3, 4], [1, 2, 3, 4]]
                 ])

t_3D.shape

torch.Size([3, 2, 4])

In [20]:
# operations
# broadcasting works
t_2D + 10

tensor([[11, 12, 13, 14],
        [11, 12, 13, 14],
        [11, 12, 13, 14]])

In [ ]:
# generate a tensor

gen_ten = th.rand(2,5,3)

gen_ten.to(device=de)
gen_ten

tensor([[[0.5107, 0.7230, 0.8936],
         [0.2934, 0.3755, 0.6000],
         [0.4604, 0.7997, 0.5661],
         [0.3786, 0.0482, 0.7519],
         [0.9721, 0.8080, 0.0290]],

        [[0.0921, 0.9937, 0.7740],
         [0.8978, 0.7310, 0.0697],
         [0.3922, 0.0214, 0.9019],
         [0.3562, 0.3653, 0.3325],
         [0.6292, 0.0323, 0.0434]]])

In [ ]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)


In [37]:
tensor_B.shape

torch.Size([3, 2])

In [ ]:
# 7   8     9
# 10  11   12

x = tensor_B.T
x

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [ ]:
tensor_A @ tensor_B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [39]:
output = torch.matmul(tensor_A, tensor_B.T)
output


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [53]:
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features  =2, # in_features = matches inner dimension of input 
                         out_features =6) # out_features = describes outer value 

linear

Linear(in_features=2, out_features=6, bias=True)

In [52]:
x = tensor_A

In [54]:
output = linear(x)
output

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

In [ ]:

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

In [31]:
import torch