- data - 

    - iris: [sepal length, sepal width, species ]
    - titanic: [ pclass sibling spouse fare age gender survival ]
    - tips: [ ]
    - penguins: [ species island lenght widths]

Columns = vectors 

In [10]:
list2= [3,4,5 , 'idrees', 4.5, [3, ['a','b'],5]]

list2[5][1][0]

'a'

In [28]:
vectorx = [3,4,[5,6,7],3]

vectorx[2][1]

6

In [38]:
vector1 = [10,4,10]

vector2 = [20,4,10]

vector3 = [30,4,10]

sum(vector1)
len(vector1) # number of element


3

In [ ]:
import numpy as np

arr = np.array(vector1)
arr

arr.max()
arr.min()
arr.mean()
arr.var() # 8.0
arr.std() # 2.82

2.8284271247461903

In [52]:
vector1 = [10,4,10]
vector2 = [20,4,10]
vector3 = [30,4,10]

matrix = [vector1, 
          vector2, 
          vector3] # 0 1 2

matrix = [[10,4,10],
          [20,4,10],
          [30,4,10]]

matrix

# how to check the dimensions?

 # [2,4,10] as a result
 # 2 as a result


[[10, 4, 10], [20, 4, 10], [30, 4, 10]]

In [89]:
matrix[0:2][8] # row  x  column

IndexError: list index out of range

In [ ]:
matrix = [[10,4,10], # 0
          [20,4,10], # 1   # 0
          [30,4,10], # 2   # 1
          [30,4,10]] # 3

matrixarr = np.array(matrix)

In [ ]:
type(matrixarr)

matrixarr.ndim

matrixarr[1][2]

#  1 2
matrixarr[1:3][2] # rows 

IndexError: index 2 is out of bounds for axis 0 with size 2

In [85]:
matrixarr[1][2]

10

In [ ]:
matrixarr * 2 # scalar multiplication

# scaler operations with arrays
# 

matrixarr.ndim
matrixarr.shape # how many rows and columns

# rows  x  columns



(4, 3)

In [ ]:
# broadcastinggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg

matrixarr + 100

array([[110, 104, 110],
       [120, 104, 110],
       [130, 104, 110],
       [130, 104, 110]])

In [114]:
a = np.array([[1, 3, 5, 6],
             [2, 8, 7, 9]]
             )
b = np.array([[10], 
              [100]])

a - b
a * b
a / b
a + b

array([[ 11,  13,  15,  16],
       [102, 108, 107, 109]])

In [ ]:
variance = np.array([145325, 423542, 24355, 3523456])
n = np.array([145, 542, 355, 3456])

In [120]:
((variance)**0.5) .round(2)

array([ 381.22,  650.8 ,  156.06, 1877.09])

In [126]:
covariance = np.array([145325, 423542])

n = np.array([145, 542, 355, 3456])

stdx , stdy = np.array([ 381.22,  650.8])

stdx
stdy


r = covariance/(stdx*stdy)
r

array([0.58575649, 1.70715621])